### PR TITLE
Resolves bug + adds e2e test to cover it + uncomment assertion

### LINKED ISSUE #253: Face with extra vertices/edges
@bgschiller @macumber Here's my first example. 

[Nov 29 2017 12_14 PM.webm.txt](https://github.com/NREL/openstudio-geometry-editor/files/1515214/Nov.29.2017.12_14.PM.webm.txt)
[floorplan.json.txt](https://github.com/NREL/openstudio-geometry-editor/files/1515216/floorplan.json.txt)

The (x,y) vertices for face id 13 is:
(-10,10)
(20,10)
(20,45)
(20,45)
(20,80)
(-10,80)
(-140,80)
(-140,-40)
(-10,-40)
(-10,-10)
(-10,10)

Note the duplicate adjacent vertices of (20,45), and thus, the extra edge. The face should have 9 edges, not 10.

### PR DESCRIPTION
**Pull request by kylem038**
Should resolve #253 + adds an e2e test for the use case + for some reason my latest merge didn't include the commit to re-enable the importFloors assertion.

### CODE REVIEW

File: src/store/modules/geometry/actions/createFaceFromPoints.js [hunk 1]
```diff
@@ -55,17 +55,16 @@ export default function createFaceFromPoints(context, payload) {
   }
 
   withPreservedComponents(context, currentStoryGeometry.id, () => {
-
     newGeoms.forEach(newGeom => context.dispatch('replaceFacePoints', newGeom));
 
     // save the face and its descendent geometry
     storeFace(faceGeometry, target, context, existingFace);
 
+    context.dispatch('trimGeometry', { geometry_id: currentStoryGeometry.id });
```
Comment (benfen) [inline src/store/modules/geometry/actions/createFaceFromPoints.js:67]: A comment explaining the importance of the ordering would be nice for the future

Comment (kylem038) [reply src/store/modules/geometry/actions/createFaceFromPoints.js:67]: Agreed. I'll add something
